In [ ]:
#Ejercicio 1
c = list(input("Introduce una secuencia de caracteres: "))
c.reverse()
print(c)

Introduce una secuencia de caracteres: buenas noches
['s', 'e', 'h', 'c', 'o', 'n', ' ', 's', 'a', 'n', 'e', 'u', 'b']


In [ ]:
#Ejercicio 2
string_1 = str(input("Ingrese el primer string: "))
string_2 = str(input("Ingrese el segundo string: "))

lista1 = list(string_1)
lista2 = list(string_2)
lista_final = []

if (len(string_1) == len(string_2)):
    largo = len(string_1)
    for i in range(largo):
        lista3 = lista1[i] + lista2[i]
        lista_final += lista3
    print(list(lista_final))
else:
    print("Los strings no son de la misma longitud")

Ingrese el primer string: hola caracola
Ingrese el segundo string: adios marieta
['h', 'a', 'o', 'd', 'l', 'i', 'a', 'o', ' ', 's', 'c', ' ', 'a', 'm', 'r', 'a', 'a', 'r', 'c', 'i', 'o', 'e', 'l', 't', 'a', 'a']


In [ ]:
#Ejercicio 3
string_1 = str(input("Introduce un string y se guardaran las consonantes en una lista: "))
string_1.lower()
lista = []
largo = len(string_1)
for i in range(largo):
    letra = string_1[i]
    if letra != "a" and letra != "e" and letra != "i" and letra != "o" and letra != "u":
        sub_lista = list(letra)
        lista += sub_lista
print(lista)

Introduce un string y se guardaran las consonantes en una lista: corazon
['c', 'r', 'z', 'n']


In [ ]:
#Ejercicio 4
word = input("Ingresa una palabra: ")
lis_word = list(word)
largo = len(word)
rango = largo//2
i = 0
if lis_word[i] == lis_word[-1-i]:
    for i in range(rango):
        if lis_word[i] == lis_word[-1-i]:
            continue
    print("La palabra es un palíndromo")
    
else:
    print("La palabra no es un palíndromo")

Ingresa una palabra: seres
La palabra es un palíndromo


In [ ]:
#Ejercicio 5
A= []
save = 0
for i in range(3):
    A.append([])
    for j in range(3):
        A[i].append(float(input("Introduce un número en la posicion ({}, {}): ".format(i, j))))
print("")
print("La matriz es: ", A)
print("")

for i in range(3):
    for j in range(0,1):
        if (A[i][j] >= A[i][j+1]) and (A[i][j] >= A[i][j+2]):
            max = A[i][j]
            print("El máximo de la fila {} es: {}".format(i, max))
        elif(A[i][j+1] >= A[i][j]) and  (A[i][j+1] >= A[i][j+2]):
            max = A[i][j+1]
            print("El máximo de la fila {} es: {}".format(i, max))
        else:
            max = A[i][j+2]
            print("El máximo de la fila {} es: {}".format(i, max))

Introduce un número en la posicion (0, 0): 4
Introduce un número en la posicion (0, 1): 8
Introduce un número en la posicion (0, 2): 8
Introduce un número en la posicion (1, 0): 9
Introduce un número en la posicion (1, 1): 2
Introduce un número en la posicion (1, 2): 7
Introduce un número en la posicion (2, 0): 6
Introduce un número en la posicion (2, 1): 7
Introduce un número en la posicion (2, 2): 2

La matriz es:  [[4.0, 8.0, 8.0], [9.0, 2.0, 7.0], [6.0, 7.0, 2.0]]

El máximo de la fila 0 es: 8.0
El máximo de la fila 1 es: 9.0
El máximo de la fila 2 es: 7.0


In [122]:
#Ejercicio 6
A = []
n = int(input("Ingrese la dimensión de la matriz nxn: "))
num = n**2 -1
num_2 = num
for i in range(n):
    A.append([])
    for j in range(n):
        A[i].insert(j, num-(num_2))
        num_2 -=1 

for i in range(n):
    for j in range(n):
        print(A[i][j], end = "  " if (A[i][j] >= 0) and (A[i][j] < 10) else " " )
    print("")
          

Ingrese la dimensión de la matriz nxn: 7
0  1  2  3  4  5  6  
7  8  9  10 11 12 13 
14 15 16 17 18 19 20 
21 22 23 24 25 26 27 
28 29 30 31 32 33 34 
35 36 37 38 39 40 41 
42 43 44 45 46 47 48 


In [ ]:
#Ejercicio 7
A = []
sum = 0
B = []
n = int(input("Ingrese el número de filas: "))
m = int(input("Ingrese el número de columnas: "))
print("")
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Ingrese el valor en la posición ({}, {}): ".format(i, j))))
print("")
print("La matriz ingresada es: ")
for i in range(n):
    for j in range(m):
        print(A[i][j], end = "  " if (A[i][j] >= 0) and (A[i][j] < 10) else " ")
    print("")

for j in range(m):
    for i in range(n):
        sum += A[i][j]
    B.append([sum])
    sum = 0
print("")
for i in range(n-1):
    if B[i] != B[i+1]:
        print("La suma de las columnas {} y {} son diferentes".format(i, i+1))
    else:
        print("La suma de las columnas {} y {} son iguales".format(i, i+1))
print(B)


Ingrese el número de filas: 3
Ingrese el número de columnas: 3

Ingrese el valor en la posición (0, 0): 5
Ingrese el valor en la posición (0, 1): 8
Ingrese el valor en la posición (0, 2): 2
Ingrese el valor en la posición (1, 0): 6
Ingrese el valor en la posición (1, 1): 4
Ingrese el valor en la posición (1, 2): 7
Ingrese el valor en la posición (2, 0): 5
Ingrese el valor en la posición (2, 1): 2
Ingrese el valor en la posición (2, 2): 8

La matriz ingresada es: 
5.0  8.0  2.0  
6.0  4.0  7.0  
5.0  2.0  8.0  

La suma de las columnas 0 y 1 son diferentes
La suma de las columnas 1 y 2 son diferentes
[[16.0], [14.0], [17.0]]


In [133]:
#Ejercicio 8
A = []
n = int(input("Ingresa el número de filas: "))
m = int(input("Ingresa el número de columnas: "))
if n == m:
    for i in range(n):
        A.append([])
        for j in range(m):
            A[i].append(float(input("Ingrese el valor en la posición ({}, {}): ".format(i, j))))
    print("")
    for i in range(n):
        for j in range(m):
            print(A[i][j], end= "  " if (A[i][j] >=0) and (A[i][j] < 10) else " ")
        print("")
    if i == j:
        req_1 = A[i][j] == 1 
    else:
        req_2 = A[i][j] == 0
    print("")
    if (req_1 == True) and (req_2 == True):
        print("La matriz introducida es una matriz identidad")
    else:
        print("")
        print("La matriz introducida no es una matriz identidad")

else:
    print("Recuerda que la matriz identidad debe ser cuadrada")

Ingresa el número de filas: 3
Ingresa el número de columnas: 3
Ingrese el valor en la posición (0, 0): 1
Ingrese el valor en la posición (0, 1): 0
Ingrese el valor en la posición (0, 2): 0
Ingrese el valor en la posición (1, 0): 0
Ingrese el valor en la posición (1, 1): 1
Ingrese el valor en la posición (1, 2): 0
Ingrese el valor en la posición (2, 0): 0
Ingrese el valor en la posición (2, 1): 0
Ingrese el valor en la posición (2, 2): 1

1.0  0.0  0.0  
0.0  1.0  0.0  
0.0  0.0  1.0  

La matriz introducida es una matriz identidad


In [ ]:
# Ejercicio 9
M = []
n = int(input("Introduce el número de filas de la matriz: "))
m = int(input("Introduce el número de columnas de la matriz: "))
for i in range(n):
    M.append([])
    for j in range(m):
        M[i].append(float(input("Ingrese el número en la posición ({}, {}): ".format(i, j))))
print("")
print("La matriz es:")   
for i in range(n) :
    for j in range(m):
        print(M[i][j], end = "  " if (M[i][j] >= 0) and (M[i][j] < 10) else " ")
    print("")
print("")
print("La matriz transpuesta de la matriz ingresada es:")
for j in range(m):
    for i in range(n):
        print(M[i][j], end = "  " if (M[i][j] >= 0) and (M[i][j] < 10) else " ")
    print("")

Introduce el número de filas de la matriz: 2
Introduce el número de columnas de la matriz: 3
Ingrese el número en la posición (0, 0): 1
Ingrese el número en la posición (0, 1): 2
Ingrese el número en la posición (0, 2): 3
Ingrese el número en la posición (1, 0): 4
Ingrese el número en la posición (1, 1): 5
Ingrese el número en la posición (1, 2): 6

La matriz es:
1.0  2.0  3.0  
4.0  5.0  6.0  

La matriz transpuesta de la matriz ingresada es:
1.0  4.0  
2.0  5.0  
3.0  6.0  


In [105]:
#Ejercicio 10 
import numpy as np
n = int(input("Ingrese la dimensión de la matriz: "))

A = np.empty((n, n))
for i in range(n):
    for j in range(n):
        if i == j:
            A[i][j] = 1
        else:
            A[i][j]=0
print(A)

Ingrese la dimensión de la matriz: 10
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
