In [9]:
# Ejercicio 1
import numpy as np
d1 = np.array([1,2,3,4,5,6,7,8,9])
print(d1)
print('\nDimensión:',d1.ndim)
print('Shape:', d1.shape)

[1 2 3 4 5 6 7 8 9]

Dimensión: 1
Shape: (9,)


In [10]:
d3 = d1.reshape(3,1,3)
print(d3)
print('\nDimensión:',d3.ndim)
print('Shape:', d3.shape)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]

Dimensión: 3
Shape: (3, 1, 3)


In [15]:
# Ejercicio 2
a1 = np.array([[-6, -5], [-4, -3], [-2, -1]])
a2 = np.array([[1, 2], [3, 4], [5, 6]])
np.concatenate((a2,a1), axis= 1)

array([[ 1,  2, -6, -5],
       [ 3,  4, -4, -3],
       [ 5,  6, -2, -1]])

In [199]:
# Ejercicio 3
a = np.array([[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]])
b = np.array_split(a, 3)
print('El array dividido en tres nos da:\n')
for i in b:
    print(i,'\n')

El array dividido en tres nos da:

[[ 1  2  3]
 [-1  0  1]] 

[[ 4  5  6]
 [-4  0  4]] 

[[ 3  2  1]
 [-3  0  3]] 



In [26]:
# Ejercicio 4
def palindroma(word):
    if word == str(word):
        letters = []
        for e in word:
            letters.append(e)
        n = len(letters)//2
        for i in range(n):
            if letters[i] != letters[-1*(i+1)]:
                return False
            else:
                continue
        return True

palindroma = np.frompyfunc(palindroma,1 ,1)

words = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]])
print(palindroma(words))

[[True False False]
 [False True False]
 [False False True]]


In [28]:
# Ejercicio 5
a = ["cena", "frío", "kayak", "remo", "sol"]
b = np.searchsorted(a, "python")
print('La palabra "python" debería ocupar el índice',b)

La palabra "python" debería ocupar el índice 3


In [200]:
# Ejercicio 6
num = np.random.randint(1, 11)
my_num = int(input('Ingresa un número entre 1 y 10: '))
count = 1
while my_num != num:
    print('¡Has fallado! ¡Prueba otra vez!\n')
    my_num = int(input('Ingresa un número entre 1 y 10: '))
    count +=1
print('¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}'.format(num))
print('Número de intentos:',count)

Ingresa un número entre 1 y 10: 1
¡Has fallado! ¡Prueba otra vez!

Ingresa un número entre 1 y 10: 2
¡Has fallado! ¡Prueba otra vez!

Ingresa un número entre 1 y 10: 3
¡Has fallado! ¡Prueba otra vez!

Ingresa un número entre 1 y 10: 4
¡Has fallado! ¡Prueba otra vez!

Ingresa un número entre 1 y 10: 5
¡Has fallado! ¡Prueba otra vez!

Ingresa un número entre 1 y 10: 6
¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el 6
Número de intentos: 6


In [156]:
# Ejercicio 7

def ingresar():
    nums = []
    while len(nums) != 5:
        n = int(input('Ingresa un número entre 1 y 20: '))
        if n >= 1 and n <= 20:
            nums.append(n)
        else:
            continue
    nums = np.array(nums)
    return nums

def metodo_ac(a, nums):
    ac = 0
    for e in a:
        if e in nums:
            ac += 1
        else:
            continue
    return ac

def metodo_pos_ac(a, nums):
    ac = 0
    pos_ac = 0
    for i in range(5):
        for j in range(len(nums)):
            if a[i] == nums[j]:
                ac += 1
                if  i == j:
                    pos_ac +=1
                else:
                    continue
            else:
                continue
    return pos_ac

a = np.random.randint(1, 20, size =5)
ac = 0
pos_ac = 0

while ac != 5 and pos_ac != 5:
    nums = ingresar()
    ac = metodo_ac(a, nums)
    pos_ac = metodo_pos_ac(a, nums)
    print('Has acertado {} números del array y {} posiciones'.format(ac, pos_ac))
    print(nums,'\n')
print('¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: {}'.format(a))

Ingresa un número entre 1 y 20: 2
Ingresa un número entre 1 y 20: 3
Ingresa un número entre 1 y 20: 4
Ingresa un número entre 1 y 20: 5
Ingresa un número entre 1 y 20: 6
Has acertado 2 números del array y 0 posiciones
[2 3 4 5 6] 

Ingresa un número entre 1 y 20: 6
Ingresa un número entre 1 y 20: 5
Ingresa un número entre 1 y 20: 3
Ingresa un número entre 1 y 20: 4
Ingresa un número entre 1 y 20: 2
Has acertado 2 números del array y 0 posiciones
[6 5 3 4 2] 

Ingresa un número entre 1 y 20: 3
Ingresa un número entre 1 y 20: 2
Ingresa un número entre 1 y 20: 5
Ingresa un número entre 1 y 20: 6
Ingresa un número entre 1 y 20: 4
Has acertado 2 números del array y 2 posiciones
[3 2 5 6 4] 

Ingresa un número entre 1 y 20: 3 
Ingresa un número entre 1 y 20: 1
Ingresa un número entre 1 y 20: 5
Ingresa un número entre 1 y 20: 1
Ingresa un número entre 1 y 20: 4
Has acertado 1 números del array y 1 posiciones
[3 1 5 1 4] 

Ingresa un número entre 1 y 20: 3
Ingresa un número entre 1 y 20: 1
Ing

In [165]:
# Ejercicio 8
x = np.array([-3, -2, -1, 0, 1, 2, 3])
a1 = np.random.choice(x, size =(3, 4))
a2 = np.random.choice(x, size =(3, 4))
print('El primer array aleatorio es:')
print(a1)
print('\nEl segundo array aleatorio es:')
print(a2)
print('\nLa suma de ambos arrrays es:')
print(np.add(a1, a2))

El primer array aleatorio es:
[[ 1  2 -2 -1]
 [-1  0 -1 -3]
 [ 2 -1 -3  1]]

El segundo array aleatorio es:
[[ 2  2  3 -1]
 [-3  0 -3  3]
 [ 2  1 -1  1]]

La suma de ambos arrrays es:
[[ 3  4  1 -2]
 [-4  0 -4  0]
 [ 4  0 -4  2]]


In [168]:
# Ejercicio 9

def vocales(words):
    words = words.lower()
    vowels = 0
    for i in range(len(words)):
        if (words[i] == "a" or words[i] =="e" or words[i] == "i" or words[i] == "o" or words[i] == "u"):
            vowels += 1
        else:
            continue
    return vowels

vowels = np.frompyfunc(vocales,1 , 1)
strings = np.array(['mariposa','flor', 'ada', 'libro', 'amanecer', 'gato', 'razonar'])

vowels(strings)

array([4, 1, 2, 2, 4, 2, 3], dtype=object)

In [196]:
# Ejercicio 10

def str_into_set(string, conjunto):
    if string in conjunto:
        return True
    else:
        return False
       
str_into_set = np.frompyfunc(str_into_set, 2, 1)

strings = np.array(['a','b','c','d','e','f','g','h','i'])
conjunto = {'a','e','i','o','u'}

str_into_set(strings, conjunto)

array([True, False, False, False, True, False, False, False, True],
      dtype=object)